"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_env(BASE_DIR / '.env')


def env(key, default=''):
    return os.environ.get(key, default)


def env_bool(key, default=False):
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(key, default):
    return int(os.environ.get(key, default))


def env_list(key, default=''):
    value = os.environ.get(key, default)
    return [item.strip() for item in value.split(',') if item.strip()]


ALADIN_TTB_KEY = env('ALADIN_TTB_KEY')
ALADIN_API_BASE_URL = env('ALADIN_API_BASE_URL', 'http://www.aladin.co.kr/ttb/api')
ALADIN_CACHE_TTL = env_int('ALADIN_CACHE_TTL', 86400)

OPENAI_API_KEY = env('OPENAI_API_KEY')
OPENAI_API_BASE_URL = env('OPENAI_API_BASE_URL', 'https://api.openai.com/v1')
OPENAI_MODEL = env('OPENAI_MODEL', 'gpt-4o-mini')
OPENAI_DAILY_QUOTE_CACHE_TTL = env_int('OPENAI_DAILY_QUOTE_CACHE_TTL', 86400)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 배포(KAIST VM) 시 반드시 DJANGO_SECRET_KEY 환경변수를 설정할 것. 아래 기본값은 로컬 개발용.
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    'django-insecure-_#bq)jkhqq-+qe@+=&&9j@_z6q-sausgku0bs+&snr(ifpjlu&',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',      # DRF 등록
    'corsheaders',         # CORS 부품 등록

    'accounts',            # B: User, Friend
    'groups',              # B: Group, GroupMember, GroupBook
    'books',               # A: Book, BookFavorite
    'annotations',         # A: Annotation, Comment, Like, AnnotationFavorite
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ★반드시 이 위치(최상단 근처)에 추가!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_ENGINE = env('DB_ENGINE', 'django.db.backends.mysql')

DATABASES = {
    'default': {
        'ENGINE': DATABASE_ENGINE,
        'NAME': env('MYSQL_DATABASE', 'booknote_db'),
        'USER': env('MYSQL_USER', 'root'),
        'PASSWORD': env('MYSQL_PASSWORD'),
        'HOST': env('MYSQL_HOST', 'localhost'),
        'PORT': env('MYSQL_PORT', '3306'),
    }
}

if 'mysql' in DATABASE_ENGINE:
    DATABASES['default']['OPTIONS'] = {
        'charset': env('MYSQL_CHARSET', 'utf8mb4'),
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env('DJANGO_LANGUAGE_CODE', 'en-us')

TIME_ZONE = env('DJANGO_TIME_ZONE', 'Asia/Seoul')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = env('DJANGO_STATIC_URL', 'static/')
STATIC_ROOT = env('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', False)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost,http://127.0.0.1,http://localhost:8080,http://127.0.0.1:8080,'
    'http://localhost:5173,http://127.0.0.1:5173,https://munjang.madcamp-kaist.org',
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'munjangseojae-local-cache',
    },
}

# 시드 데이터: python manage.py loaddata seed
FIXTURE_DIRS = [BASE_DIR / 'fixtures']

# DRF 공통 규약 (docs/api-spec.md 기준)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 공개 endpoint는 GET, 🔒 endpoint는 각 뷰에서 IsAuthenticated 지정
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardPagination',
    'PAGE_SIZE': env_int('DRF_PAGE_SIZE', 20),
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'UNAUTHENTICATED_USER': 'django.contrib.auth.models.AnonymousUser',
}

# JWT: 무상태 (refresh token 미사용, 로그아웃은 204만 반환 — api-spec 기준)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env_int('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 10080)),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
