# Generated by Django 6.0.6 on 2026-07-05 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUESTION', 'Question'), ('DISCUSSION', 'Discussion'), ('REVIEW', 'Review'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('passage', models.CharField(max_length=500)),
                ('review', models.TextField(blank=True, default='')),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('group', 'Group'), ('private', 'Private')], default='public', max_length=10)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='books.book')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUESTION', 'Question'), ('DISCUSSION', 'Discussion'), ('REVIEW', 'Review'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='annotations.annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotation_comments',
            },
        ),
        migrations.CreateModel(
            name='AnnotationFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='annotations.annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_annotations',
                'constraints': [models.UniqueConstraint(fields=('user', 'annotation'), name='unique_annotation_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('annotation', 'Annotation'), ('comment', 'Comment')], max_length=10)),
                ('target_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_like_target')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='unique_like')],
            },
        ),
    ]
