# Generated by Django 6.0.6 on 2026-07-08 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('date_label', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('book_title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=list)),
                ('cover_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('isbn', models.CharField(blank=True, default='', max_length=20)),
                ('source_event', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_curations',
                'indexes': [models.Index(fields=['month', 'day'], name='daily_curation_month_day_idx')],
            },
        ),
    ]
